# Script para limpiar archivos obsoletos
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$archiveDir = "_archive_$timestamp"

Write-Host "Creando carpeta de archivo..."
New-Item -ItemType Directory -Path $archiveDir -Force | Out-Null

$archivos = @(
    "ANALISIS-COMPLETO-DIFERENCIAS-BACKUP23-VS-ACTUAL.md",
    "ANALISIS-COMPLETO-RENTABILIDAD.md",
    "ANALISIS-DEPENDENCIAS-SUBTOTAL-USD.md",
    "ANALISIS-ERROR-FACTURACION.md",
    "ANALISIS-EXHAUSTIVO-ERROR.md",
    "ANALISIS-RIESGO-NUEVOS-USUARIOS.md",
    "ANALISIS-ROLES-PERSONALIZADOS.md",
    "DIAGNOSTICO-COMPLETO-UTILITYRATE.md",
    "DIAGNOSTICO-ESPACIO-DERECHO-PROFUNDO.md",
    "DIAGNOSTICO-FORMULA-SUBTOTAL.md",
    "DIAGNOSTICO-MODAL-VERSION-SIMPLE.md",
    "DEBUG-PROFILEMODAL-NO-ABRE.md",
    "PROBLEMA-ADICIONAL-DETECTADO.md",
    "PROBLEMA-CRITICO-SCHEMA-USUARIOS.md",
    "PROBLEMA-MENU-USUARIOS-FALTA.md",
    "PROBLEMA-REAL-IDENTIFICADO.md",
    "PROBLEMA-VENDEDOR-RESUELTO.md",
    "PROBLEMAS-IDENTIFICADOS-DAYRE.md",
    "REPORTE-CAMBIOS-PERDIDOS.md",
    "REPORTE-INCONSISTENCIAS-NOMBRES-COMPLETO.md",
    "ARREGLOS-USUARIO-DAYRE.md",
    "CORRECCION-3-ERRORES-CRITICOS.md",
    "CORRECCION-ESPACIO-DERECHO-MEDICAMENTOS.md",
    "CORRECCION-FINAL-IT-MEDICINES.md",
    "CORRECCION-FINAL-RECEIPTITEM.md",
    "CORRECCION-MIDDLEWARE-AUTH.md",
    "CORRECCION-NOMBRES-COMPLETADA.md",
    "FIX-BOTON-IR-AL-INICIO.md",
    "FIX-BUSQUEDA-TOPBAR.md",
    "FIX-COMPLETO-ENTRADAS-SNAKE-CASE.md",
    "FIX-COMPLETO-PARAMETROS-ARRAY.md",
    "FIX-CRITICO-LOGIN-SIN-ROLES.md",
    "FIX-ERROR-ENTRADAS-RECEIPTITEM.md",
    "FIX-ERROR-SALIDAS-400.md",
    "FIX-FINAL-PROFILEMODAL-FUNCIONANDO.md",
    "FIX-NOTIFICACIONES-TOPBAR.md",
    "FIX-PARAMETROS-NO-SE-CARGAN.md",
    "FIX-PRECIO-PROPUESTO-USD.md",
    "FIX-PROFILEMODAL-PAGINA-BLANCA.md",
    "FIX-PROFILEMODAL-USEEFFECT.md",
    "FIX-REPORTE-FINANZAS.md",
    "FIX-SALIDAS-COSTO-UNITARIO.md",
    "SOLUCION-FINAL-ESPACIO-DERECHO.md",
    "NAVEGACION-Y-LOGOUT-ARREGLADOS.md",
    "RESTAURACION-SALEFORM-COMPLETADA.md",
    "FASE-1-COMPLETADA.md",
    "FASE-2-COMPLETADA.md",
    "FASE-2-CORRECCION-VENDEDOR.md",
    "FASE-3-COMPLETADA-EXITOSAMENTE.md",
    "FASE-3-CORRECCION-ERRORES.md",
    "FASE-3-CORRECCION-STARTPANEL.md",
    "FASE-3-INSTRUCCIONES-PRUEBA.md",
    "FASE1-COMPLETADA-FINAL.md",
    "FASE1-COMPLETADA.md",
    "FASE1-FACTURACION-INSTRUCCIONES.md",
    "FASE2-COMPLETADA.md",
    "ESTANDARIZACION-DISENO-COMPLETADA.md",
    "ESTANDARIZACION-PASO-1.md",
    "IMPLEMENTACION-CAMBIAR-CONTRASENA.md",
    "IMPLEMENTACION-PERMISOS-COMPLETADA.md",
    "BUSQUEDA-TOPBAR-FUNCIONANDO.md",
    "FECHA-HORA-TOPBAR-IMPLEMENTADO.md",
    "NUEVAS-NOTIFICACIONES-IMPLEMENTADAS.md",
    "RENTABILIDAD-IMPLEMENTADO.md",
    "SELECTOR-MONEDA-IMPLEMENTADO.md",
    "TOPBAR-CORRECCIONES.md",
    "TOPBAR-IMPLEMENTADO.md",
    "TODAS-PAGINAS-ANCHO-COMPLETO.md",
    "CAMBIO-NOMBRE-REPORTE-FINANCIERO.md",
    "SUGERENCIAS-BARRA-BUSQUEDA.md",
    "BACKUP-ANTES-REPORTES.md",
    "BACKUP-FASE2-INFO.md",
    "BACKUP-Y-COMMIT-26DIC-171858.md",
    "COMMIT-BUSQUEDA-26DIC-2025.md",
    "COMMIT-CORRECCIONES-CRITICAS-27DIC.md",
    "CAMBIOS-SALIDAS-EN-BACKUP-DIA-23.md",
    "COMPARACION-BACKUPS-22-VS-23.md",
    "COMPARACION-DETALLADA-ACTUAL-VS-BACKUP23.md",
    "RESUMEN-CAMBIOS-DIA-22.md",
    "REVISION-COMPLETA-HASACCESSTOROUTE.md",
    "REVISION-EXHAUSTIVA-CODIGO.md",
    "VERIFICACION-FINAL-COMPLETA.md",
    "SISTEMA-100-FUNCIONAL.md",
    "SCHEMA-PRISMA-ACTUALIZADO.md",
    "FORMULA-SUBTOTAL-USD-SALIDAS.md",
    "SERVIDORES-INICIADOS.md",
    "GIT-LOCAL-CONFIGURADO.md"
)

$movedCount = 0
foreach ($archivo in $archivos) {
    if (Test-Path $archivo) {
        Move-Item -Path $archivo -Destination $archiveDir -Force
        $movedCount++
    }
}

Write-Host "Archivos movidos: $movedCount"
Write-Host "Carpeta: $archiveDir"
Write-Host "Limpieza completada!"

